version: '3.4'

services:
  app:
    build:
      context: .
      target: app-container
    restart: always
    container_name: compass_app
    environment:
      ENV: localdev
      AUTH: SAML_MOCK
      GOOGLE_ANALYTICS_KEY: ${GOOGLE_ANALYTICS_KEY}
      GWS_ENV: Mock
    volumes:
      - ./compass:/app/compass
      - statics-volume:/static
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
  devtools:
    build:
      context: .
      target: wpack
    restart: always
    container_name: compass_devtools
    ports:
      - "${BUNDLE_ANALYZER_PORT:-8888}:8888" # Required when environment.BUNDLE_ANALYZER is true
    environment:
      VUE_DEVTOOLS: "True"
      BUNDLE_ANALYZER: "True"
    volumes:
      - ./compass:/app/compass # expose main django app so webpack-loader can output bundles here
      - ./compass_vue:/app/compass_vue
      - statics-volume:/static
    command: npx webpack --watch --mode=development
    stdin_open: true
    tty: true
volumes:
  statics-volume:
