# Generated by Django 3.2.13 on 2022-05-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField()),
                ('actions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_key', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uwnetid', models.TextField(unique=True)),
                ('uwregid', models.TextField(unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uwnetid'], name='compass_use_uwnetid_6b52fe_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uwregid'], name='compass_use_uwregid_cc2325_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['system_key'], name='compass_stu_system__11b092_idx'),
        ),
        migrations.AddField(
            model_name='group',
            name='contact_types',
            field=models.ManyToManyField(to='compass.ContactType'),
        ),
        migrations.AddField(
            model_name='group',
            name='topics',
            field=models.ManyToManyField(to='compass.Topic'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.contacttype'),
        ),
        migrations.AddField(
            model_name='contact',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.group'),
        ),
        migrations.AddField(
            model_name='contact',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.student'),
        ),
        migrations.AddField(
            model_name='contact',
            name='topics',
            field=models.ManyToManyField(to='compass.Topic'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.user'),
        ),
    ]
