# Generated by Django 3.2.6 on 2021-08-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sis_term_id', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('quarter', models.TextField(null=True)),
                ('label', models.TextField(null=True)),
                ('last_day_add', models.DateField(null=True)),
                ('last_day_drop', models.DateField(null=True)),
                ('first_day_quarter', models.DateField(null=True)),
                ('census_day', models.DateField(null=True)),
                ('last_day_instruction', models.DateField(null=True)),
                ('grading_period_open', models.DateTimeField(null=True)),
                ('aterm_grading_period_open', models.DateTimeField(null=True)),
                ('grade_submission_deadline', models.DateTimeField(null=True)),
                ('last_final_exam_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
