# Generated by Django 3.2.13 on 2022-06-01 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('notes', models.TextField()),
                ('actions', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('slug', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('time', models.TimeField()),
                ('notes', models.TextField()),
                ('actions', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical contact',
                'verbose_name_plural': 'historical contacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_key', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uwnetid', models.TextField(unique=True)),
                ('uwregid', models.TextField(unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uwnetid'], name='compass_use_uwnetid_6b52fe_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uwregid'], name='compass_use_uwregid_cc2325_idx'),
        ),
        migrations.AddField(
            model_name='student',
            name='programs',
            field=models.ManyToManyField(to='compass.Program'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compass.user'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='contact_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compass.contacttype'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compass.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='contact_topics',
            field=models.ManyToManyField(to='compass.ContactTopic'),
        ),
        migrations.AddField(
            model_name='group',
            name='programs',
            field=models.ManyToManyField(to='compass.Program'),
        ),
        migrations.AddField(
            model_name='contact',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.user'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_topics',
            field=models.ManyToManyField(to='compass.ContactTopic'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.contacttype'),
        ),
        migrations.AddField(
            model_name='contact',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.student'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['system_key'], name='compass_stu_system__11b092_idx'),
        ),
    ]
