# Generated by Django 3.2.6 on 2021-09-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(null=True)),
                ('is_dept_adviser', models.BooleanField(null=True)),
                ('full_name', models.TextField(null=True)),
                ('pronouns', models.TextField(null=True)),
                ('email_address', models.TextField(null=True)),
                ('phone_number', models.TextField(null=True)),
                ('uwnetid', models.TextField(null=True)),
                ('regid', models.TextField(null=True)),
                ('program', models.TextField(null=True)),
                ('booking_url', models.TextField(null=True)),
                ('metadata', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_abbr_code', models.TextField(null=True)),
                ('major_name', models.TextField(null=True)),
                ('major_full_name', models.TextField(null=True)),
                ('major_short_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.BigIntegerField(unique=True)),
                ('uw_net_id', models.TextField(null=True)),
                ('student_name', models.TextField(null=True)),
                ('birthdate', models.DateField(null=True)),
                ('student_email', models.TextField(null=True)),
                ('external_email', models.TextField(null=True)),
                ('local_phone_number', models.TextField(null=True)),
                ('gender', models.TextField(null=True)),
                ('gpa', models.TextField(null=True)),
                ('total_credits', models.TextField(null=True)),
                ('campus_desc', models.TextField(null=True)),
                ('class_desc', models.TextField(null=True)),
                ('enrollment_status', models.TextField(null=True)),
                ('adviser', models.ManyToManyField(to='compass.Adviser')),
                ('intended_major', models.ManyToManyField(related_name='intended_major', to='compass.Major')),
                ('major', models.ManyToManyField(related_name='major', to='compass.Major')),
            ],
        ),
    ]
