# Generated by Django 3.2.13 on 2022-06-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='actions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='actions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
