# Generated by Django 3.2.13 on 2022-06-17 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_topics',
            field=models.ManyToManyField(to='compass.ContactTopic'),
        ),
        migrations.CreateModel(
            name='SpecialProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.accessgroup')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='special_programs',
            field=models.ManyToManyField(to='compass.SpecialProgram'),
        ),
    ]
