# Generated by Django 3.2.13 on 2022-06-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0002_auto_20220617_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='special_programs',
        ),
        migrations.AddField(
            model_name='contacttopic',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='SpecialProgram',
        ),
    ]
