# Generated by Django 3.2.7 on 2021-09-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0002_adviser_major_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='major_full_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='honors_program_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='perm_addr_4digit_zip',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='perm_addr_5digit_zip',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='perm_addr_city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='perm_addr_country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='perm_addr_line1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='perm_addr_line2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='perm_addr_postal_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='perm_addr_state',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='resident_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='special_program_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='special_program_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_preferred_first_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_preferred_last_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_preferred_middle_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_uw_credits',
            field=models.TextField(null=True),
        ),
    ]
