# Generated by Django 3.2.7 on 2022-09-20 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0003_auto_20220621_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='author',
            new_name='app_user',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='pub_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='historicalcontact',
            old_name='author',
            new_name='app_user',
        ),
        migrations.RenameField(
            model_name='historicalcontact',
            old_name='pub_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='time',
        ),
        migrations.AddField(
            model_name='contact',
            name='checkin_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='checkin_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
