# Generated by Django 3.2.7 on 2021-09-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0003_auto_20210920_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_status',
        ),
        migrations.AddField(
            model_name='student',
            name='campus_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='class_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_status_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='exemption_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='exemption_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='honors_program_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registered_in_quarter',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='resident_code',
            field=models.TextField(null=True),
        ),
    ]
