# Generated by Django 3.2.7 on 2021-09-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0004_auto_20210923_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_program_code', models.TextField(null=True)),
                ('special_program_desc', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='special_program_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='special_program_desc',
        ),
        migrations.AddField(
            model_name='student',
            name='special_program',
            field=models.ManyToManyField(to='compass.SpecialProgram'),
        ),
    ]
