# Generated by Django 3.2.7 on 2022-09-23 22:26

from django.db import migrations, models
from django.utils.text import slugify



def update_slugs(apps, schema_editor):
    ContactTopic = apps.get_model("compass", "ContactTopic")
    ContactType = apps.get_model("compass", "ContactType")
    Program = apps.get_model("compass", "Program")

    for instance in ContactTopic.objects.all():
        instance.slug = slugify(instance.name)
        instance.save()

    for instance in ContactType.objects.all():
        instance.slug = slugify(instance.name)
        instance.save()

    for instance in Program.objects.all():
        instance.slug = slugify(instance.name)
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0004_auto_20220920_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttopic',
            name='slug',
            field=models.SlugField(null=True, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacttype',
            name='slug',
            field=models.SlugField(null=True, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(null=True, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(update_slugs,
                             reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contacttopic',
            name='slug',
            field=models.SlugField(null=False, unique=True),
            preserve_default=False
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='slug',
            field=models.SlugField(null=False, unique=True),
            preserve_default=False
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(null=False, unique=True),
            preserve_default=False
        ),
        migrations.AddField(
            model_name='contacttopic',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
