# Generated by Django 3.2.10 on 2021-12-11 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0005_auto_20210923_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.TextField(null=True)),
                ('sign_in', models.TextField(null=True)),
                ('activity', models.TextField(null=True)),
                ('assignment', models.TextField(null=True)),
                ('grade', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='retention',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compass.retention'),
        ),
    ]
