# Generated by Django 3.2.16 on 2022-11-08 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0005_auto_20220923_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('editable', models.BooleanField(default=True)),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.accessgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compass.contactmethod'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='contact_method',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compass.contactmethod'),
        ),
    ]
