# Generated by Django 3.2.7 on 2021-09-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0005_auto_20210923_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='canvas_user_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='uw_reg_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uw_net_id',
            field=models.TextField(unique=True),
        ),
    ]
