# Generated by Django 3.2.18 on 2023-04-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0006_auto_20221108_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True)),
                ('editable', models.BooleanField(default=True)),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.accessgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AffiliationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusivity_count', models.SmallIntegerField()),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.accessgroup')),
                ('exclusivity_group', models.ManyToManyField(to='compass.Affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.SmallIntegerField()),
                ('end_year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('actively_advised', models.BooleanField(default=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.affiliation')),
                ('cohorts', models.ManyToManyField(to='compass.Cohort')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='programs',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.AddField(
            model_name='studentaffiliation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.student'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='affiliation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compass.affiliationgroup'),
        ),
    ]
