# Generated by Django 3.2.18 on 2023-04-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0007_auto_20230413_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliationgroup',
            name='name',
            field=models.CharField(default='Program', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliationgroup',
            name='slug',
            field=models.SlugField(default='program'),
            preserve_default=False,
        ),
    ]
