# Generated by Django 3.2.19 on 2023-05-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0008_auto_20230421_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='affiliation_group',
        ),
        migrations.DeleteModel(
            name='AffiliationGroup',
        ),
    ]
