# Generated by Django 3.2.19 on 2023-05-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0009_auto_20230512_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('editable', models.BooleanField(default=False)),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.accessgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_eligible', models.BooleanField(default=False)),
                ('course_code', models.CharField(max_length=32)),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.accessgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.student')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.visittype')),
            ],
        ),
    ]
