# Generated by Django 3.2.19 on 2023-06-01 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0010_visit_visittype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('editable', models.BooleanField(default=True)),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.accessgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='visit',
            name='ic_eligible',
        ),
        migrations.AlterField(
            model_name='visit',
            name='course_code',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='StudentEligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility', models.ManyToManyField(to='compass.EligibilityType')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.student')),
            ],
        ),
    ]
