# Generated by Django 3.2.19 on 2023-06-08 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0011_auto_20230531_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='app_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compass.appuser'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compass.contactmethod'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compass.contacttype'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compass.student'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compass.visittype'),
        ),
    ]
