# Generated by Django 4.2.8 on 2023-12-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0012_auto_20230607_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='trans_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='trans_id',
            field=models.IntegerField(null=True),
        ),
    ]
