# Generated by Django 4.2.9 on 2024-01-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0013_contact_trans_id_historicalcontact_trans_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMADContactQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('process_attempted_date', models.DateTimeField(null=True)),
                ('processing_error', models.TextField(null=True)),
                ('stack_trace', models.TextField(null=True)),
                ('processing_attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
