# Generated by Django 4.2.10 on 2024-02-14 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0016_alter_specialprogram_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('component', models.CharField(max_length=50)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.appuser')),
            ],
            options={
                'unique_together': {('app_user', 'key', 'component')},
            },
        ),
    ]
