# Generated by Django 4.2.13 on 2024-06-25 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0017_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='RADWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(choices=[('AUT', 'autumn'), ('WIN', 'winter'), ('SPR', 'spring'), ('SUM', 'summer')], max_length=255)),
                ('week', models.IntegerField()),
                ('key', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RADImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(auto_now=True)),
                ('import_status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=255)),
                ('week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compass.radweek')),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('activity_score', models.FloatField()),
                ('assignment_score', models.FloatField()),
                ('grade_score', models.FloatField()),
                ('prediction_score', models.FloatField()),
                ('signin_score', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.student')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.radweek')),
            ],
        ),
    ]
