# Generated by Django 4.2.17 on 2024-12-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0019_alter_courseanalyticsscores_prediction_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAlertStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_status', models.CharField(choices=[('SC', 'success'), ('WR', 'warning'), ('DN', 'danger')], max_length=2, null=True)),
                ('uwnetid', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['uwnetid'], name='compass_stu_uwnetid_b88dfd_idx')],
            },
        ),
    ]
