# Generated by Django 4.2.17 on 2024-12-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0019_alter_courseanalyticsscores_prediction_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAlertStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_status', models.CharField(choices=[('SC', 'success'), ('WR', 'warning'), ('DN', 'danger')], max_length=2, null=True)),
                ('uwnetid', models.CharField(max_length=50)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.radweek')),
            ],
            options={
                'indexes': [models.Index(fields=['uwnetid', 'week'], name='compass_stu_uwnetid_c84ddd_idx')],
                'unique_together': {('uwnetid', 'week')},
            },
        ),
    ]
