# Generated by Django 5.2.8 on 2025-11-13 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0020_studentalertstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentalertstatus',
            name='source_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compass.radweek'),
        ),
    ]
