# Generated by Django 4.2.21 on 2025-05-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0020_studentalertstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmethod',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacttopic',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
