# Generated by Django 5.2.10 on 2026-07-10

from django.db import migrations, models
from django.db.models import Count


def validate_group_scoped_uniqueness(apps, schema_editor):
    checks = [
        ("Affiliation", "name"),
        ("Affiliation", "slug"),
        ("ContactType", "name"),
        ("ContactType", "slug"),
        ("ContactMethod", "name"),
        ("ContactMethod", "slug"),
        ("ContactTopic", "name"),
        ("ContactTopic", "slug"),
        ("EligibilityType", "name"),
        ("EligibilityType", "slug"),
        ("VisitType", "name"),
        ("VisitType", "slug"),
    ]

    for model_name, field_name in checks:
        model = apps.get_model("compass", model_name)
        duplicates = (
            model.objects.values("access_group_id", field_name)
            .annotate(item_count=Count("id"))
            .filter(item_count__gt=1)
        )
        if duplicates.exists():
            sample = duplicates[0]
            raise RuntimeError(
                f"Cannot apply scoped uniqueness: {model_name}.{field_name} "
                f"has duplicates in access_group_id={sample['access_group_id']} "
                f"for value='{sample[field_name]}'"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0022_radimport_prediction_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='slug',
            field=models.SlugField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmethod',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmethod',
            name='slug',
            field=models.SlugField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacttopic',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacttopic',
            name='slug',
            field=models.SlugField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eligibilitytype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eligibilitytype',
            name='slug',
            field=models.SlugField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visittype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visittype',
            name='slug',
            field=models.SlugField(max_length=50),
        ),
        migrations.RunPython(
            validate_group_scoped_uniqueness,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='affiliation',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'name'),
                name='compass_affiliation_ag_name_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='affiliation',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'slug'),
                name='compass_affiliation_ag_slug_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='contacttype',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'name'),
                name='compass_contacttype_ag_name_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='contacttype',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'slug'),
                name='compass_contacttype_ag_slug_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'name'),
                name='compass_contactmethod_ag_name_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'slug'),
                name='compass_contactmethod_ag_slug_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='contacttopic',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'name'),
                name='compass_contacttopic_ag_name_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='contacttopic',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'slug'),
                name='compass_contacttopic_ag_slug_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='eligibilitytype',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'name'),
                name='compass_eligibilitytype_ag_name_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='eligibilitytype',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'slug'),
                name='compass_eligibilitytype_ag_slug_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='visittype',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'name'),
                name='compass_visittype_ag_name_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='visittype',
            constraint=models.UniqueConstraint(
                fields=('access_group', 'slug'),
                name='compass_visittype_ag_slug_uniq',
            ),
        ),
    ]
