# Generated by Django 5.2.11 on 2026-04-21 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0023_access_group_scoped_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitTutoringOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('editable', models.BooleanField(default=False)),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.accessgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='tutoring_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compass.visittutoringoption'),
        ),
    ]
