# Generated by Django 5.2.11 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0024_visittutoringoption_visit_tutoring_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='visittype',
            name='is_compass_visits_program_area',
            field=models.BooleanField(default=False),
        ),
    ]
