autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
resources:
  limits:
    cpu: 250m
    memory: 1.0Gi
  requests:
    cpu: 50m
    memory: 256Mi
targetAverageUtilization: 100

ingress:
  enabled: true
  tls:
    compass:
      secretName: compass.uw.edu-ingress-cert
      hosts:
        - compass.uw.edu
  hosts:
    compass:
      host: compass.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"
    nginx.ingress.kubernetes.io/proxy-body-size: "2M"
    nginx.ingress.kubernetes.io/limit-rps: "10"

lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
  podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true

externalService:
  enabled: true
  name: compass-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.4
  servicePort: 5432
database:
  engine: postgres
  name: compass-prod
  hostname: compass-db-service
  secretName: compass.uw.edu-sql-secrets

repo: compass
instance: prod

memcached:
  enabled: true
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate

certs:
  mounted: true
  certPath: /certs/compass.uw.edu-ic.cert
  keyPath: /certs/compass.uw.edu-ic.key
  secretName: compass.uw.edu-ic-certs

cronjob:
  enabled: true
  jobs:
    - name: clear-sessions
      schedule: "20 9 * * 0"
      command: ["/scripts/management_command.sh"]
      args: ["clearsessions"]

environmentVariables:
  - name: ENV
    value: prod

  - name: SWS_ENV
    value: PROD
  - name: SWS_TIMEOUT
    value: "10"

  - name: PWS_ENV
    value: PROD
  - name: PWS_TIMEOUT
    value: "10"

  - name: GWS_ENV
    value: PROD
  - name: GWS_TIMEOUT
    value: "5"

  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://compass.uw.edu/saml2
  - name: SAML_FORCE_AUTHN
    value: "True"
  - name: SP_USE_2FA
    value: "True"

  - name: CLUSTER_CNAME
    value: compass.uw.edu

  - name: UW_PERSON_CLIENT_ENV
    value: PROD

externalSecrets:
  enabled: true
  secrets:
    - name: compass.uw.edu-secrets
      externalKey: compass/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: group-id-admin
          property: group-id-admin
        - name: group-id-support
          property: group-id-support
        - name: google-analytics-key
          property: google-analytics-key
    - name: compass.uw.edu-sql-secrets
      externalKey: compass/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: compass.uw.edu-shared-secrets
      externalKey: compass/shared/secrets
      data:
        - name: person-db-user
          property: person-db-user
        - name: person-db-pass
          property: person-db-pass
        - name: person-db-host
          property: person-db-host
        - name: person-db-port
          property: person-db-port
        - name: person-db-database
          property: person-db-database
    - name: compass.uw.edu-ic-certs
      externalKey: compass/prod/ic-certs
      data:
        - name: compass.uw.edu-ic.cert
          property: compass.uw.edu-ic.cert
        - name: compass.uw.edu-ic.key
          property: compass.uw.edu-ic.key
    - name: compass.uw.edu-uw-idp-cert
      externalKey: idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: compass.uw.edu-secrets
    secretKey: django-secret
  adminGroup:
    name: ADMIN_GROUP
    secretName: compass.uw.edu-secrets
    secretKey: group-id-admin
  supportGroup:
    name: SUPPORT_GROUP
    secretName: compass.uw.edu-secrets
    secretKey: group-id-support
  googleAnalyticsKey:
    name: GOOGLE_ANALYTICS_KEY
    secretName: compass.uw.edu-secrets
    secretKey: google-analytics-key
  samlSPCert:
    name: SP_CERT
    secretName: compass.uw.edu-ic-certs
    secretKey: compass.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: compass.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
  personDBUser:
    name: UW_PERSON_DB_USERNAME
    secretName: compass.uw.edu-shared-secrets
    secretKey: person-db-user
  personDBPass:
    name: UW_PERSON_DB_PASSWORD
    secretName: compass.uw.edu-shared-secrets
    secretKey: person-db-pass
  personDBHost:
    name: UW_PERSON_DB_HOSTNAME
    secretName: compass.uw.edu-shared-secrets
    secretKey: person-db-host
  personDBPort:
    name: UW_PERSON_DB_PORT
    secretName: compass.uw.edu-shared-secrets
    secretKey: person-db-port
  personDBDatabase:
    name: UW_PERSON_DB_DATABASE
    secretName: compass.uw.edu-shared-secrets
    secretKey: person-db-database

daemon:
  enabled: true
  daemons:
    - name: process-omad-contact-queue
      replicaCount: 1
      command: ["/scripts/management_daemon.sh"]
      args: ["--delay", "5", "process_omad_contacts"]
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 64Mi
