autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
resources:
  limits:
    cpu: 250m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 128Mi
targetAverageUtilization: 100

ingress:
  enabled: true
  tls:
    compass:
      secretName: test.compass.uw.edu-ingress-cert
      hosts:
        - test.compass.uw.edu
  hosts:
    compass:
      host: test.compass.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"

lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
  podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true

externalService:
  enabled: true
  name: compass-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.4
  servicePort: 5432
database:
  engine: postgres
  name: compass-test
  hostname: compass-db-service
  secretName: test.compass.uw.edu-sql-secrets

repo: compass
instance: test
namespace:
  enabled: true

memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate

gcsCredentials:
  mounted: true
  secretName: test.compass.uw.edu-gcs-credentials

certs:
  mounted: true
  certPath: /certs/compass.uw.edu-ic.cert
  keyPath: /certs/compass.uw.edu-ic.key
  secretName: test.compass.uw.edu-ic-certs

cronjob:
  enabled: true
  jobs:
    - name: load-rad-data
      schedule: "0 4 * * 1"
      command: ["/scripts/management_command.sh"]
      args: ["load_rad_data"]
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 200m
          memory: 512Mi

environmentVariables:
  - name: ENV
    value: test

  - name: SWS_ENV
    value: PROD
  - name: SWS_TIMEOUT
    value: "10"

  - name: PWS_ENV
    value: PROD
  - name: PWS_TIMEOUT
    value: "10"

  - name: GWS_ENV
    value: PROD
  - name: GWS_TIMEOUT
    value: "5"

  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://test.compass.uw.edu/saml2

  - name: CLUSTER_CNAME
    value: test.compass.uw.edu

externalSecrets:
  enabled: true
  secrets:
    - name: test.compass.uw.edu-secrets
      externalKey: compass/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: group-id-admin
          property: group-id-admin
        - name: group-id-support
          property: group-id-support
        - name: google-analytics-key
          property: google-analytics-key
        - name: storage-bucket-name
          property: storage-bucket-name
    - name: test.compass.uw.edu-sql-secrets
      externalKey: compass/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: test.compass.uw.edu-shared-secrets
      externalKey: compass/shared/secrets
      data:
        - name: person-db-user
          property: person-db-user
        - name: person-db-pass
          property: person-db-pass
        - name: person-db-host
          property: person-db-host
        - name: person-db-port
          property: person-db-port
        - name: person-db-database
          property: person-db-database
        - name: storage-project-id
          property: storage-project-id
    - name: test.compass.uw.edu-gcs-credentials
      externalKey: compass/shared/gcs-credentials
      data:
        - name: credentials.json
          property: credentials.json
    - name: test.compass.uw.edu-ic-certs
      externalKey: compass/prod/ic-certs
      data:
        - name: compass.uw.edu-ic.cert
          property: compass.uw.edu-ic.cert
        - name: compass.uw.edu-ic.key
          property: compass.uw.edu-ic.key
    - name: test.compass.uw.edu-sp-cert
      externalKey: compass/test/ic-certs
      data:
        - name: test.compass.uw.edu-ic.cert
          property: test.compass.uw.edu-ic.cert
    - name: test.compass.uw.edu-uw-idp-cert
      externalKey: idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.compass.uw.edu-secrets
    secretKey: django-secret
  adminGroup:
    name: ADMIN_GROUP
    secretName: test.compass.uw.edu-secrets
    secretKey: group-id-admin
  supportGroup:
    name: SUPPORT_GROUP
    secretName: test.compass.uw.edu-secrets
    secretKey: group-id-support
  googleAnalyticsKey:
    name: GOOGLE_ANALYTICS_KEY
    secretName: test.compass.uw.edu-secrets
    secretKey: google-analytics-key
  samlSPCert:
    name: SP_CERT
    secretName: test.compass.uw.edu-sp-cert
    secretKey: test.compass.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: test.compass.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
  personDBUser:
    name: UW_PERSON_DB_USER
    secretName: test.compass.uw.edu-shared-secrets
    secretKey: person-db-user
  personDBPass:
    name: UW_PERSON_DB_PASSWORD
    secretName: test.compass.uw.edu-shared-secrets
    secretKey: person-db-pass
  personDBHost:
    name: UW_PERSON_DB_HOST
    secretName: test.compass.uw.edu-shared-secrets
    secretKey: person-db-host
  personDBPort:
    name: UW_PERSON_DB_PORT
    secretName: test.compass.uw.edu-shared-secrets
    secretKey: person-db-port
  personDBDatabase:
    name: UW_PERSON_DB_NAME
    secretName: test.compass.uw.edu-shared-secrets
    secretKey: person-db-database
  storageBucketName:
    name: STORAGE_BUCKET_NAME
    secretName: test.compass.uw.edu-secrets
    secretKey: storage-bucket-name
  storageProjectId:
    name: STORAGE_PROJECT_ID
    secretName: test.compass.uw.edu-shared-secrets
    secretKey: storage-project-id

daemon:
  enabled: true
  daemons:
    - name: process-omad-contact-queue
      replicaCount: 1
      command: ["/scripts/management_daemon.sh"]
      args: ["--delay", "5", "process_omad_contacts"]
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 25m
          memory: 64Mi
