ingress:
  enabled: true
  tls:
    compass:
      secretName: test.compass.uw.edu-ingress-cert
      hosts:
        - test.compass.uw.edu
  hosts:
    compass:
      host: test.compass.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"

lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
  podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true

externalService:
  enabled: true
  name: compass-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.4
  servicePort: 5432
database:
  engine: postgres
  name: compass-test
  hostname: compass-db-service
  secretName: test.compass.uw.edu-sql-secrets

repo: compass
instance: test

memcached:
  enabled: false

certs:
  mounted: true
  certPath: /certs/test.compass.uw.edu-ic.cert
  keyPath: /certs/test.compass.uw.edu-ic.key
  secretName: test.compass.uw.edu-ic-certs

environmentVariables:
  - name: ENV
    value: test

  - name: SWS_ENV
    value: PROD
  - name: SWS_TIMEOUT
    value: "10"

  - name: GWS_ENV
    value: PROD
  - name: GWS_TIMEOUT
    value: "5"

  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://test.compass.uw.edu/saml2

  - name: CLUSTER_CNAME
    value: test.compass.uw.edu

externalSecrets:
  enabled: true
  secrets:
    - name: test.compass.uw.edu-secrets
      externalKey: compass/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: group-id-admin
          property: group-id-admin
        - name: group-id-support
          property: group-id-support
        - name: google-analytics-key
          property: google-analytics-key
    - name: test.compass.uw.edu-sql-secrets
      externalKey: compass/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: test.compass.uw.edu-ic-certs
      externalKey: compass/test/ic-certs
      data:
        - name: test.compass.uw.edu-ic.cert
          property: test.compass.uw.edu-ic.cert
        - name: test.compass.uw.edu-ic.key
          property: test.compass.uw.edu-ic.key
    - name: test.compass.uw.edu-uw-idp-cert
      externalKey: idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.compass.uw.edu-secrets
    secretKey: django-secret
  adminGroup:
    name: ADMIN_GROUP
    secretName: test.compass.uw.edu-secrets
    secretKey: group-id-admin
  supportGroup:
    name: SUPPORT_GROUP
    secretName: test.compass.uw.edu-secrets
    secretKey: group-id-support
  googleAnalyticsKey:
    name: GOOGLE_ANALYTICS_KEY
    secretName: test.compass.uw.edu-secrets
    secretKey: google-analytics-key
  samlSPCert:
    name: SP_CERT
    secretName: test.compass.uw.edu-ic-certs
    secretKey: test.compass.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: test.compass.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
