ingress:
  enabled: true
  tls:
    compass:
      secretName: test.compass.uw.edu-ingress-cert
      hosts:
        - test.compass.uw.edu
  hosts:
    compass:
      host: test.compass.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"

lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
  podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true

externalService:
  enabled: true
  name: compass-db-service
  type: ClusterIP
  serviceAddress:
  servicePort: 5432
database:
  engine: postgres
  name: compass-test
  hostname: compass-db-service
  secretName: test.compass.uw.edu-sql-secrets

repo: compass
instance: test
image:
  repository: gcr.io/uwit-mci-axdd/compass
  tag: IMAGE_TAG

memcached:
  enabled: false

environmentVariables:
  - name: ENV
    value: test
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://test.compass.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: test.compass.uw.edu
  - name: EDW_HOSTNAME
    value:

externalSecrets:
  enabled: true
  secrets:
    - name: test.compass.uw.edu-secrets
      externalKey: axdd/kv/data/compass/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: access-group-id
          property: access-group-id
        - name: google-analytics-key
          property: google-analytics-key
    - name: test.compass.uw.edu-shared-secrets
      externalKey: axdd/kv/data/compass/shared/secrets
      data:
        - name: edw-username
          property: edw-username
        - name: edw-password
          property: edw-password
    - name: test.compass.uw.edu-sql-secrets
      externalKey: axdd/kv/data/compass/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: test.compass.uw.edu-ic-certs
      externalKey: axdd/kv/data/compass/test/ic-certs
      data:
        - name: test.compass.uw.edu-ic.cert
          property: test.compass.uw.edu-ic.cert
    - name: test.compass.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.compass.uw.edu-secrets
    secretKey: django-secret
  accessGroup:
    name: ACCESS_GROUP
    secretName: test.compass.uw.edu-secrets
    secretKey: access-group-id
  googleAnalyticsKey:
    name: GOOGLE_ANALYTICS_KEY
    secretName: test.compass.uw.edu-secrets
    secretKey: google-analytics-key
  samlSPCert:
    name: SP_CERT
    secretName: test.compass.uw.edu-ic-certs
    secretKey: test.compass.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: test.compass.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
  edwUsername: EDW_USERNAME
    name: EDW_USERNAME
    secretName: test.compass.uw.edu-shared-secrets
    secretKey: edw-username
  edwPassword: EDW_PASSWORD
    name: EDW_PASSWORD
    secretName: test.compass.uw.edu-shared-secrets
    secretKey: edw-password
